#!/usr/bin/env sh

{{ansible_managed|comment(decoration='#')}}

# Shell variables

SHELL='/bin/sh'
PATH='/sbin:/bin:/usr/sbin:/usr/bin'

# Commands

WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }

GREP=$(${WHICH} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
SLEEP=$(${WHICH} sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
ZPOOL=$(${WHICH} zpool) || { echo "Error: Command 'zpool' not found."; exit 127; }

{% if (zfs_monitor_mail_state == True) %}
MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
{% endif %}

# Environment variables

HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
TIME_START=$(${DATE} '+%s')
USER='{{file_owner_zfs_scrub_pools}}'
LOCKFILE='/var/tmp/zfs_scrub-pools.lock'
TEXTFILE_COLLECTOR='{{zfs_monitor_prom_textfile_collector}}'

ZFS_SCRUB_POOLS_POOLS='{% for item in zfs_scrub_pools_pools %}{{item}}{% if not loop.last %} {% endif %}{% endfor %}'

{% if (zfs_monitor_mail_state == True) %}
MAIL_FROM_ADDRESS='{{zfs_monitor_mail_from_address}}'
MAIL_TO_ADDRESS='{% for item in zfs_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
MAIL_SUBJECT='zfs: Scrub Pool - Error ({{ansible_hostname}})'
{% endif %}

# Functions

{% if (zfs_monitor_mail_state == True) %}
mail_error() {
    local exit_code=${1}
    local message=${2}
    local mail_body="ERROR

Message     : ${message}
Exit Code   : ${exit_code}
Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')

SCRIPT

Name        : ${SCRIPT_NAME}
Type        : Shell script
PID         : ${$}

SYSTEM

Hostname    : {{ansible_hostname}}
FQDN        : {{ansible_fqdn}}"

    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
}
{% endif %}

{% if (zfs_monitor_prom_state == True) %}
update_prom() {
    local exit_code=${1}
    local time_exec=${2}

    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
        ${ECHO} -e "# HELP zfs_scrub_pools_exit The script's exit code.\n"\
"# TYPE zfs_scrub_pools_exit counter\n"\
"zfs_scrub_pools_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/zfs_scrub_pools_exit.prom"

        if [ -z "${TIME_START}" ]; then
            ${RM} -f "${TEXTFILE_COLLECTOR}/zfs_scrub_pools_start.prom"
        else
            ${ECHO} -e "# HELP zfs_scrub_pools_start The script's start time in epoch.\n"\
"# TYPE zfs_scrub_pools_start counter\n"\
"zfs_scrub_pools_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/zfs_scrub_pools_start.prom"
        fi

        if [ -z "${time_exec}" ]; then
            ${RM} -f "${TEXTFILE_COLLECTOR}/zfs_scrub_pools_duration.prom"
        else
            ${ECHO} -e "# HELP zfs_scrub_pools_duration The script's execution duration in seconds.\n"\
"# TYPE zfs_scrub_pools_duration counter\n"\
"zfs_scrub_pools_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/zfs_scrub_pools_duration.prom"
        fi
    fi
}
{% endif %}

check_script_user() {
    if [ "$(${WHOAMI})" != "${USER}" ]; then
        local exit_code=77
        local message="Please run script as user '${USER}'"

        if [ -t 1 ]; then
            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
        fi

        exit ${exit_code}
    fi
}

create_lockfile() {
    if [ ! -e "${LOCKFILE}" ]; then
        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
    else
        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
    fi
}

remove_lockfile() {
    if [ -e "${LOCKFILE}" ]; then
        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
    else
        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
    fi
}

log_and_exit_on_error() {
    local exit_code=${1}
    local message=${2}

    if [ ${exit_code} -ne 0 ]; then
        ${RM} -f ${LOCKFILE}

        if [ -t 1 ]; then
            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
        fi

        ${LOGGER} -t ${SCRIPT} "${message}"

{% if (zfs_monitor_mail_state == True) %}
        mail_error ${exit_code} "${message}"
{% endif %}

{% if (zfs_monitor_prom_state == True) %}
        update_prom "${exit_code}" "${time_exec}"
{% endif %}

        exit ${exit_code}
    fi
}

log_and_exit() {
    local time_end=$(${DATE} '+%s')
    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
    local exit_code=${1}
    local message=${2}

    if [ -t 1 ]; then
        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
    fi

    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"

{% if (zfs_monitor_prom_state == True) %}
    update_prom "${exit_code}" "${time_exec}"
{% endif %}

    exit ${exit_code}
}

get_scrub_status() {
    local time_initial=0

    # Wait while 'scrub in progress'
    while ${ZPOOL} status | ${GREP} 'scrub in progress' >/dev/null 2>&1 ; do
        if [ "${time_initial}" -lt 300 ]; then
            time_initial=$(${EXPR} "${time_initial}" + 5)
            ${SLEEP} "${time_initial}"
        else
            ${SLEEP} "${time_initial}"
        fi
    done
}

scrub_zfs_pools() {
    for pool in ${ZFS_SCRUB_POOLS_POOLS} ; do
        # Wait until previous scrub has finished
        get_scrub_status

        # Scrub next ZFS pool
        ${ZPOOL} scrub ${pool}
        log_and_exit_on_error "${?}" "Unable to scrub ZFS pool: '${pool}'"
    done
}

check_zfs_pools() {
    for pool in ${ZFS_SCRUB_POOLS_POOLS} ; do
        # Wait until previous scrub has finished
        get_scrub_status

        # Get next ZFS pool status
        local zfs_pool_status="$(${ZPOOL} status -xv ${pool})"
        log_and_exit_on_error "${?}" "Unable to get ZFS pool status: '${pool}'"

        # Check next ZFS pool status
        ${ECHO} "${zfs_pool_status}" | ${GREP} 'healthy' >/dev/null 2>&1
        if [ "${?}" -eq 0 ]; then
            message="ZFS pool has been scrubbed and is healthy: '${pool}'"
            ${LOGGER} -t ${SCRIPT} "${message}"
        else
            log_and_exit_on_error "${?}" "ZFS pool is unhealthy: '${pool}'"
        fi
    done
}

# Establish run order
main() {
    check_script_user
    create_lockfile
    scrub_zfs_pools
    check_zfs_pools
    remove_lockfile
    if [ -z "${ZFS_SCRUB_POOLS_POOLS}" ]; then
        log_and_exit '0' 'No ZFS pools have been specified for scrubbing.'
    else
        log_and_exit '0' 'Specified ZFS pools have been scrubbed and are healthy.'
    fi
}

main
