#!/usr/bin/env sh

{{ansible_managed|comment(decoration='#')}}

# SHELL VARIABLES

SHELL='/bin/sh'
PATH='/sbin:/bin:/usr/sbin:/usr/bin'

# COMMANDS

which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
grep=$(${which} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
{% if (apt_monitor_mail_state is match('true|yes|enable')) %}
mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
{% endif %}
rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
tr=$(${which} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
wc=$(${which} wc) || { echo "Error: Command 'wc' not found."; exit 127; }
whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }

apt_get=$(${which} apt-get) || { echo "Error: Command 'apt-get' not found."; exit 127; }

# VARIABLES

host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
time_start=$(${date} '+%s')
user='{{file_owner_apt_check_update}}'
lockfile='/var/tmp/apt_check-update.lock'
retval=0
severity='Debug'
message='Please check log files for more information.'

textfile_collector='{{apt_monitor_prom_textfile_collector}}'

{% if (apt_monitor_mail_state is match('true|yes|enable')) %}
mail_from_address='{{apt_monitor_mail_from_address}}'
mail_to_address='{% for item in apt_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
mail_subject='apt: Check Update - Error ({{ansible_hostname}})'
{% endif %}

# FUNCTIONS

{% if (apt_monitor_mail_state is match('true|yes|enable')) %}
mail_error() {
  retval="$1"
  severity="$2"
  message="$3"
  mail_body="ERROR

Message     : ${message}
Severity    : ${severity}
Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')

SCRIPT

Name        : apt_check-update
Type        : Shell script
PID         : $$

SYSTEM

Hostname    : {{ansible_hostname}}
FQDN        : {{ansible_fqdn}}"

  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
}
{% endif %}

{% if (apt_monitor_prom_state is match('true|yes|enable')) %}
update_prom() {
  retval="$1"
  time_start="$2"
  time_exec="$3"

  if [ -w "${textfile_collector}" ]; then
    ${echo} -e "# HELP apt_check_update_exit The script's exit code.\n"\
"# TYPE apt_check_update_exit counter\n"\
"apt_check_update_exit ${retval}" > "${textfile_collector}/apt_check_update_exit.prom"

    if [ -z "${time_start}" ] ; then
      ${rm} -f "${textfile_collector}/apt_check_update_start.prom"
    else
      ${echo} -e "# HELP apt_check_update_start The script's start time in epoch.\n"\
"# TYPE apt_check_update_start counter\n"\
"apt_check_update_start ${time_start}" > "${textfile_collector}/apt_check_update_start.prom"
    fi

    if [ -z "${time_exec}" ] ; then
      ${rm} -f "${textfile_collector}/apt_check_update_duration.prom"
    else
      ${echo} -e "# HELP apt_check_update_duration The script's execution duration in seconds.\n"\
"# TYPE apt_check_update_duration counter\n"\
"apt_check_update_duration ${time_exec}" > "${textfile_collector}/apt_check_update_duration.prom"
    fi

    if [ -z "${packages}" ] ; then
      ${rm} -f "${textfile_collector}/apt_check_update_packages.prom"
    else
      ${echo} -e "# HELP apt_check_update_packages The number of pending updates in packages.\n"\
"# TYPE apt_check_update_packages counter\n"\
"apt_check_update_packages ${packages}" > "${textfile_collector}/apt_check_update_packages.prom"
    fi
  fi
}
{% endif %}

check_script_user() {
  if [ "$(${whoami})" != "${user}" ]; then
    retval=77
    severity='Error'
    message="Please run script as user '${user}'"
    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
    exit "${retval}"
  fi
}

create_lockfile() {
  if [ ! -e "${lockfile}" ]; then
    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
  else
    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
  fi
}

remove_lockfile() {
  if [ -e "${lockfile}" ]; then
    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
  else
    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
  fi
}

log_and_exit_on_error() {
  retval="$1"
  severity="$2"
  message="$3"
  if [ "${retval}" -ne 0 ]; then
    ${rm} -f "${lockfile}"

    if [ -t 1 ] ; then
      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
    fi

    ${logger} -t "${script}" "${severity}: ${message}"

{% if (apt_monitor_mail_state is match('true|yes|enable')) %}
    mail_error "${retval}" "${severity}" "${message}"
{% endif %}

{% if (apt_monitor_prom_state is match('true|yes|enable')) %}
    update_prom "${retval}" "${time_start}" "${time_exec}"
{% endif %}

    exit "${retval}"
  fi
}

log_and_exit() {
  retval="$1"
  severity="$2"
  message="$3"

  time_end=$(${date} '+%s')
  time_exec=$(${expr} "${time_end}" - "${time_start}")
  time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')

  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"

{% if (apt_monitor_prom_state is match('true|yes|enable')) %}
  update_prom "${retval}" "${time_start}" "${time_exec}"
{% endif %}

  exit "${retval}"
}

# SCRIPT

check_script_user

create_lockfile

# Resynchronize package index files
${apt_get} --quiet update > /dev/null 2>&1
log_and_exit_on_error "$?" 'Error' 'Unable to resynchronize package index files.'

# Check for pending updates
packages=$(${apt_get} --quiet --simulate dist-upgrade | ${grep} '^Inst ' | ${wc} -l)
log_and_exit_on_error "$?" 'Error' 'Unable to check for updates.'

remove_lockfile

if [ "${packages}" -ne 0 ]; then
  log_and_exit '100' 'Warn' "System has pending updates (${packages})."
else
  log_and_exit '0' 'Info' 'System is up-to-date.'
fi
