#!/usr/bin/env sh

{{ansible_managed|comment(decoration='#')}}

# Shell variables

SHELL='/bin/sh'
PATH='/sbin:/bin:/usr/sbin:/usr/bin'

# Commands

WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }

AWK=$(${WHICH} awk) || { echo "Error: Command 'awk' not found."; exit 127; }
CAT=$(${WHICH} cat) || { echo "Error: Command 'cat' not found."; exit 127; }
CURL=$(${WHICH} curl) || { echo "Error: Command 'curl' not found."; exit 127; }
GREP=$(${WHICH} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
SERVICE="{{service}}"
SUDO=$(${WHICH} sudo) || { echo "Error: Command 'sudo' not found."; exit 127; }

{% if (unbound_adblock_monitor_mail_state == True) %}
MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
{% endif %}

# Environment variables

HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
TIME_START=$(${DATE} '+%s')
USER='{{file_owner_unbound_adblock_update_list}}'
LOCKFILE='/var/tmp/unbound-adblock_update-list.lock'
TEXTFILE_COLLECTOR='{{unbound_adblock_monitor_prom_textfile_collector}}'

{% if (unbound_adblock_monitor_mail_state == True) %}
MAIL_FROM_ADDRESS='{{unbound_adblock_monitor_mail_from_address}}'
MAIL_TO_ADDRESS='{% for item in unbound_adblock_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
MAIL_SUBJECT='Unbound AdBlock: Update List - Error ({{ansible_hostname}})'
{% endif %}

# Functions

{% if (unbound_adblock_monitor_mail_state == True) %}
mail_error() {
    local exit_code=${1}
    local message=${2}
    local mail_body="ERROR

Message     : ${message}
Exit Code   : ${exit_code}
Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')

SCRIPT

Name        : ${SCRIPT_NAME}
Type        : Shell script
PID         : ${$}

SYSTEM

Hostname    : {{ansible_hostname}}
FQDN        : {{ansible_fqdn}}"

    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
}
{% endif %}

{% if (unbound_adblock_monitor_prom_state == True) %}
update_prom() {
    local exit_code=${1}
    local time_exec=${2}

    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
        ${ECHO} -e "# HELP unbound_adblock_update_list_exit The script's exit code.\n"\
"# TYPE unbound_adblock_update_list_exit counter\n"\
"unbound_adblock_update_list_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/unbound_adblock_update_list_exit.prom"

        if [ -z "${TIME_START}" ]; then
            ${RM} -f "${TEXTFILE_COLLECTOR}/unbound_adblock_update_list_start.prom"
        else
            ${ECHO} -e "# HELP unbound_adblock_update_list_start The script's start time in epoch.\n"\
"# TYPE unbound_adblock_update_list_start counter\n"\
"unbound_adblock_update_list_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/unbound_adblock_update_list_start.prom"
        fi

        if [ -z "${time_exec}" ]; then
            ${RM} -f "${TEXTFILE_COLLECTOR}/unbound_adblock_update_list_duration.prom"
        else
            ${ECHO} -e "# HELP unbound_adblock_update_list_duration The script's execution duration in seconds.\n"\
"# TYPE unbound_adblock_update_list_duration counter\n"\
"unbound_adblock_update_list_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/unbound_adblock_update_list_duration.prom"
        fi
    fi
}
{% endif %}

check_script_user() {
    if [ "$(${WHOAMI})" != "${USER}" ]; then
        local exit_code=77
        local message="Please run script as user '${USER}'"

        if [ -t 1 ]; then
            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
        fi

        exit ${exit_code}
    fi
}

create_lockfile() {
    if [ ! -e "${LOCKFILE}" ]; then
        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
    else
        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
    fi
}

remove_lockfile() {
    if [ -e "${LOCKFILE}" ]; then
        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
    else
        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
    fi
}

log_and_exit_on_error() {
    local exit_code=${1}
    local message=${2}

    if [ ${exit_code} -ne 0 ]; then
        ${RM} -f ${LOCKFILE}

        if [ -t 1 ]; then
            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
        fi

        ${LOGGER} -t ${SCRIPT} "${message}"

{% if (unbound_adblock_monitor_mail_state == True) %}
        mail_error ${exit_code} "${message}"
{% endif %}

{% if (unbound_adblock_monitor_prom_state == True) %}
        update_prom "${exit_code}" "${time_exec}"
{% endif %}

        exit ${exit_code}
    fi
}

log_and_exit() {
    local time_end=$(${DATE} '+%s')
    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
    local exit_code=${1}
    local message=${2}

    if [ -t 1 ]; then
        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
    fi

    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"

{% if (unbound_adblock_monitor_prom_state == True) %}
    update_prom "${exit_code}" "${time_exec}"
{% endif %}

    exit ${exit_code}
}

get_upstream_hosts_file() {
   ${CURL} -s -o {{file_dst_hosts}} "{{unbound_adblock_source}}"
    log_and_exit_on_error "${?}" 'Unable to download upstream hosts file.'
}

transform_hosts_file() {
    ${CAT} {{file_dst_hosts}} | ${GREP} '^0\.0\.0\.0' | ${AWK} '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2" A 0.0.0.0\""}' >{{file_dst_adblock_conf}}
    log_and_exit_on_error "${?}" 'Unable to transform hosts file into Unbound syntax.'
}

restart_unbound_service() {
    ${SUDO} ${SERVICE} restart {{service_name_unbound}} >/dev/null 2>&1
    log_and_exit_on_error "${?}" 'Unable to restart Unbound service.'
}

check_unbound_service() {
    ${SUDO} ${SERVICE} status {{service_name_unbound}} >/dev/null 2>&1
    log_and_exit_on_error "${?}" 'Unable to check Unbound service.'
}

# Establish run order
main() {
    check_script_user
    create_lockfile
    get_upstream_hosts_file
    transform_hosts_file
    restart_unbound_service
    check_unbound_service
    remove_lockfile
    log_and_exit '0' 'Unbound AdBlock list has been updated.'
}

main
