#!/usr/bin/env sh

{{ansible_managed|comment(decoration='#')}}

# Shell variables

SHELL='/bin/sh'
PATH='/sbin:/bin:/usr/sbin:/usr/bin'

# Commands

WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
{% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
{% endif %}
RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }

FSTRIM=$(${WHICH} fstrim) || { echo "Error: Command 'fstrim' not found."; exit 127; }

# Environment variables

HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
TIME_START=$(${DATE} '+%s')
USER='{{file_owner_fstrim_discard_blocks}}'
LOCKFILE='/var/tmp/fstrim_discard-blocks.lock'
LOG_FILE='{{file_dst_fstrim_log}}'
TEXTFILE_COLLECTOR='{{fstrim_monitor_prom_textfile_collector}}'

{% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
MAIL_FROM_ADDRESS='{{fstrim_monitor_mail_from_address}}'
MAIL_TO_ADDRESS='{% for item in fstrim_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
MAIL_SUBJECT='fstrim: Discard Blocks - Error ({{ansible_hostname}})'
{% endif %}

# Functions

{% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
mail_error() {
    exit_code=${1}
    message=${2}
    mail_body="ERROR

Message     : ${message}
Exit Code   : ${exit_code}
Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')

SCRIPT

Name        : fstrim_discard-blocks
Type        : Shell script
PID         : ${$}

SYSTEM

Hostname    : {{ansible_hostname}}
FQDN        : {{ansible_fqdn}}"

    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
}
{% endif %}

{% if (fstrim_monitor_prom_state is match('true|yes|enable')) %}
update_prom() {
    local exit_code=${1}
    local time_exec=${2}

    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
        if [ -z "${exit_code}" ]; then
            ${ECHO} -e "# HELP fstrim_discard_blocks_exit The script's exit code.\n"\
"# TYPE fstrim_discard_blocks_exit counter\n"\
"fstrim_discard_blocks_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_exit.prom"
        fi

        if [ -z "${TIME_START}" ]; then
            ${RM} -f "${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_start.prom"
        else
            ${ECHO} -e "# HELP fstrim_discard_blocks_start The script's start time in epoch.\n"\
"# TYPE fstrim_discard_blocks_start counter\n"\
"fstrim_discard_blocks_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_start.prom"
        fi

        if [ -z "${time_exec}" ]; then
            ${RM} -f "${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_duration.prom"
        else
            ${ECHO} -e "# HELP fstrim_discard_blocks_duration The script's execution duration in seconds.\n"\
"# TYPE fstrim_discard_blocks_duration counter\n"\
"fstrim_discard_blocks_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_duration.prom"
        fi
    fi
}
{% endif %}

check_script_user() {
    if [ "$(${WHOAMI})" != "${USER}" ]; then
        local exit_code=77
        local message="Please run script as user '${USER}'"

        if [ -t 1 ]; then
            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
        fi

        exit ${exit_code}
    fi
}

create_lockfile() {
    if [ ! -e "${LOCKFILE}" ]; then
        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
    else
        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
    fi
}

remove_lockfile() {
    if [ -e "${LOCKFILE}" ]; then
        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
    else
        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
    fi
}

log_and_exit_on_error() {
    local exit_code=${1}
    local message=${2}
    if [ ${exit_code} -ne 0 ]; then
        ${RM} -f ${LOCKFILE}

        if [ -t 1 ]; then
            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
        fi

        ${LOGGER} -t ${SCRIPT} "${message}"

{% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
        mail_error ${exit_code} "${message}"
{% endif %}

{% if (fstrim_monitor_prom_state is match('true|yes|enable')) %}
        update_prom "${exit_code}" "${time_exec}"
{% endif %}

        add_log_header 'fstrim failed'

        exit ${exit_code}
    fi
}

log_and_exit() {
    local time_end=$(${DATE} '+%s')
    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
    local exit_code=0
    local message='Unused blocks discarded successfully.'

    if [ -t 1 ]; then
        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
    fi

    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"

{% if (fstrim_monitor_prom_state is match('true|yes|enable')) %}
    update_prom "${exit_code}" "${time_exec}"
{% endif %}

    exit ${exit_code}
}

add_log_header() {
    local name=${1}
    local name_upper=$(${ECHO} ${name} | ${TR} '[:lower:]' '[:upper:]')
    local date_time=$(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
    echo "# ${name_upper} | ${date_time}" >>${LOG_FILE}
}

discard_unused_blocks() {
    ${FSTRIM} --all --verbose >>${LOG_FILE} 2>&1
    log_and_exit_on_error "${?}" 'Unable to discard unused blocks.'
}

# Establish run order
main() {
    check_script_user
    create_lockfile
    add_log_header 'fstrim started'
    discard_unused_blocks
    add_log_header 'fstrim successful'
    remove_lockfile
    log_and_exit
}

main
