#!/usr/bin/env sh

{{ansible_managed|comment(decoration='#')}}

/usr/bin/sudo -u pod_forgejo /usr/bin/podman exec -i --env SSH_ORIGINAL_COMMAND="${SSH_ORIGINAL_COMMAND}" pod_forgejo-forgejo sh "${@}"
